packageExtensions:
  "@types/body-parser@*":
    dependencies:
      connect: "*"
  "@types/bootstrap@*":
    dependencies:
      jquery: "*"
  "@types/cookies@*":
    dependencies:
      connect: "*"
      express: "*"
      keygrip: "*"
  "@types/debug@*":
    dependencies:
      ms: "*"
  "@types/express-serve-static-core@*":
    dependencies:
      events: "*"
      qs: "*"
      range-parser: "*"
  "@types/express@*":
    dependencies:
      body-parser: "*"
      qs: "*"
      serve-static: "*"
  "@types/imagesloaded@*":
    dependencies:
      jquery: "*"
  "@types/koa-compose@*":
    dependencies:
      koa: "*"
  "@types/koa-compress@*":
    dependencies:
      koa: "*"
  "@types/koa-send@*":
    dependencies:
      koa: "*"
  "@types/koa-static@*":
    dependencies:
      koa: "*"
      koa-send: "*"
  "@types/koa@*":
    dependencies:
      accepts: "*"
      content-disposition: "*"
      cookies: "*"
      events: "*"
      http-assert: "*"
      http-errors: "*"
      keygrip: "*"
      koa-compose: "*"
  "@types/koa__cors@*":
    dependencies:
      koa: "*"
  "@types/koa__router@*":
    dependencies:
      koa: "*"
  "@types/serve-static@*":
    dependencies:
      mime: "*"
  "@types/yargs@*":
    dependencies:
      yargs-parser: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  typedoc@*:
    dependencies:
      "@gjsify/typedoc-plugin-remote-search": "*"
      "@gjsify/typedoc-theme": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.5.0.cjs
