packageExtensions:
  "@gjsify/typedoc-plugin-remote-search@*":
    dependencies:
      typedoc: "*"
  "@gjsify/typedoc-theme@*":
    dependencies:
      typedoc: "*"
  "chalk@5.0.0":
    dependencies:
      "#ansi-styles": "npm:ansi-styles@*"
      "#supports-color": "npm:supports-color@*"
  "ts-for-gir@*":
    dependencies:
      "ts-node": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
